version: "3.8"

services:
  backend:
    image: aachman7696/arogya-backend:latest
    container_name: arogya-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    image: aachman7696/arogya-frontend:latest
    container_name: arogya-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  mongo:
    image: mongo:6
    container_name: arogya-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
