version: "3.8"

services:
  backend:
    build: ./backend
    container_name: arogya-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
      args:
        # Pass the Vite variable from frontend/.env into the Docker build
        - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
    container_name: arogya-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env   # makes sure vite variables are available

  mongo:
    image: mongo:6
    container_name: arogya-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
